# Generated by Django 5.2.12 on 2026-05-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_timesheet_archive_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_key', models.CharField(db_index=True, default='default', max_length=100)),
                ('token_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_sessions',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_key', models.CharField(db_index=True, default='default', max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('pin_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_profiles',
                'indexes': [models.Index(fields=['customer_key', 'last_name', 'first_name'], name='idx_empprofile_customer_name'), models.Index(fields=['customer_key', 'is_active'], name='idx_empprofile_customer_active')],
                'constraints': [models.UniqueConstraint(fields=('customer_key', 'phone_number'), name='uniq_employee_profile_customer_phone')],
            },
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='api.employeeprofile'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['customer_key', 'employee_profile', 'week_year', 'week_number'], name='idx_timesheets_profile_week'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('customer_key', 'employee_profile', 'week_year', 'week_number', 'sheet_id'), name='uniq_timesheet_profile_week_sheet'),
        ),
        migrations.AddField(
            model_name='employeesession',
            name='employee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.employeeprofile'),
        ),
        migrations.AddIndex(
            model_name='employeesession',
            index=models.Index(fields=['customer_key', 'employee_profile', 'expires_at'], name='idx_empsess_prof_exp'),
        ),
        migrations.AddConstraint(
            model_name='employeesession',
            constraint=models.UniqueConstraint(fields=('customer_key', 'token_hash'), name='uniq_employee_session_customer_token'),
        ),
    ]
